"""Generate a supplementary local SHAP waterfall for the 55-feature XGBoost model.

The manuscript Figure 12 is the ordered global SHAP summary generated by
``20_pipeline_55feat.py``. This script keeps the local waterfall output in the
revision figures folder only, so it cannot overwrite the manuscript Figure 12.
"""

from __future__ import annotations

import ctypes
import importlib
import json
import math
import os
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Patch
import numpy as np


# Load an optional libomp override before importing xgboost through the pipeline.
LIBOMP_PATH = os.environ.get("LIBOMP_DYLIB", "")
if os.path.exists(LIBOMP_PATH):
    ctypes.cdll.LoadLibrary(LIBOMP_PATH)

SCRIPT_DIR = Path(__file__).resolve().parent
PLAN_DIR = SCRIPT_DIR.parent
RESULTS_DIR = PLAN_DIR / "results"
FIGURES_DIR = PLAN_DIR / "figures"
sys.path.insert(0, str(SCRIPT_DIR))

pipeline = importlib.import_module("20_pipeline_55feat")

PALETTE = {
    "blue": "#0F4D92",
    "blue_2": "#3775BA",
    "red": "#B64342",
    "red_2": "#E9A6A1",
    "orange": "#C95F2A",
    "gray": "#6B7280",
    "dark": "#1F2937",
    "light_gray": "#F3F5F7",
    "border": "#D5DCE5",
}


def apply_style() -> None:
    """Apply the restrained V4 paper style to the waterfall figure."""
    plt.rcParams.update(
        {
            "font.family": "sans-serif",
            "font.sans-serif": ["Arial", "Helvetica", "DejaVu Sans", "sans-serif"],
            "font.size": 12,
            "axes.spines.top": False,
            "axes.spines.right": False,
            "axes.linewidth": 1.45,
            "axes.labelsize": 12,
            "xtick.labelsize": 11,
            "ytick.labelsize": 10.5,
            "legend.frameon": False,
            "figure.dpi": 150,
            "savefig.dpi": 300,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )


def logit(probability: np.ndarray) -> np.ndarray:
    """Convert probabilities to log-odds with numerical clipping."""
    clipped = np.clip(probability, 1e-9, 1 - 1e-9)
    return np.log(clipped / (1 - clipped))


def load_tuned_xgboost_params() -> dict:
    """Load the stored Optuna parameters used by the 55-feature pipeline."""
    params_path = RESULTS_DIR / "optuna_55feat_params.json"
    with params_path.open("r", encoding="utf-8") as f:
        tuned_params = json.load(f)
    return tuned_params["xgboost"]


def select_representative_positive(model, x_test_df, y_test: np.ndarray) -> tuple[int, np.ndarray, np.ndarray]:
    """Choose a correctly predicted positive case nearest the median positive confidence."""
    probabilities = model.predict_proba(x_test_df.values)[:, 1]
    predictions = (probabilities >= 0.5).astype(int)
    candidate_idx = np.where((y_test == 1) & (predictions == 1))[0]
    if len(candidate_idx) == 0:
        candidate_idx = np.where(y_test == 1)[0]
    if len(candidate_idx) == 0:
        candidate_idx = np.arange(len(y_test))

    target_probability = float(np.median(probabilities[candidate_idx]))
    selected = int(candidate_idx[np.argmin(np.abs(probabilities[candidate_idx] - target_probability))])
    return selected, probabilities, predictions


def build_waterfall_items(
    feature_names: list[str],
    feature_values: np.ndarray,
    shap_row: np.ndarray,
    top_n: int = 12,
) -> list[dict[str, object]]:
    """Return top local SHAP contributions plus one aggregate residual contribution."""
    order = np.argsort(-np.abs(shap_row))
    top_indices = list(order[:top_n])
    top_items = []
    for idx in top_indices:
        value = float(feature_values[idx])
        top_items.append(
            {
                "feature": feature_names[idx],
                "feature_value": value,
                "contribution": float(shap_row[idx]),
            }
        )

    remaining_indices = order[top_n:]
    if len(remaining_indices) > 0:
        top_items.append(
            {
                "feature": f"Other {len(remaining_indices)} features",
                "feature_value": math.nan,
                "contribution": float(shap_row[remaining_indices].sum()),
            }
        )
    return top_items


def feature_label(item: dict[str, object]) -> str:
    """Format a feature name and its processed value for the y-axis."""
    name = str(item["feature"])
    value = item["feature_value"]
    if isinstance(value, float) and math.isnan(value):
        return name
    return f"{name} = {float(value):.3g}"


def plot_waterfall(
    items: list[dict[str, object]],
    base_value: float,
    final_value: float,
    predicted_probability: float,
    output_pdf: Path,
    output_png: Path,
) -> None:
    """Draw and save a publication-style horizontal SHAP waterfall."""
    apply_style()
    fig, ax = plt.subplots(figsize=(9.4, 6.2))
    ax.set_facecolor("#FFFFFF")
    fig.patch.set_facecolor("#FFFFFF")

    cumulative = base_value
    y_positions = np.arange(len(items))[::-1]

    x_values = [base_value, final_value]
    for item in items:
        next_value = cumulative + float(item["contribution"])
        x_values.extend([cumulative, next_value])
        cumulative = next_value

    x_min, x_max = min(x_values), max(x_values)
    pad = max((x_max - x_min) * 0.16, 0.35)
    ax.set_xlim(x_min - pad, x_max + pad)

    cumulative = base_value
    for y, item in zip(y_positions, items):
        contribution = float(item["contribution"])
        next_value = cumulative + contribution
        left = min(cumulative, next_value)
        width = abs(contribution)
        color = PALETTE["red"] if contribution >= 0 else PALETTE["blue_2"]

        ax.barh(
            y,
            width,
            left=left,
            height=0.58,
            color=color,
            edgecolor="white",
            linewidth=0.8,
            zorder=3,
        )
        ax.plot([next_value, next_value], [y - 0.37, y + 0.37], color=PALETTE["gray"], lw=0.75, alpha=0.75)

        sign = "+" if contribution >= 0 else ""
        text_x = next_value + (0.035 if contribution >= 0 else -0.035)
        ha = "left" if contribution >= 0 else "right"
        ax.text(
            text_x,
            y,
            f"{sign}{contribution:.3f}",
            va="center",
            ha=ha,
            fontsize=9.4,
            color=PALETTE["dark"],
        )
        cumulative = next_value

    ax.axvline(base_value, color=PALETTE["gray"], lw=1.2, linestyle="--", zorder=2)
    ax.axvline(final_value, color=PALETTE["red"], lw=1.5, linestyle="-", zorder=2)
    ax.grid(axis="x", color=PALETTE["border"], linewidth=0.8, alpha=0.65)
    ax.set_axisbelow(True)

    ax.set_yticks(y_positions)
    ax.set_yticklabels([feature_label(item) for item in items])
    ax.set_xlabel("Model output (log-odds for self-repaid)")
    ax.set_ylim(-0.85, y_positions[0] + 1.0)

    top_y = y_positions[0] + 0.62
    ax.text(base_value, top_y, f"base = {base_value:.2f}", ha="center", va="bottom", fontsize=9.5, color=PALETTE["gray"])
    ax.text(
        final_value,
        top_y,
        f"prediction = {final_value:.2f} (p={predicted_probability:.2f})",
        ha="center",
        va="bottom",
        fontsize=9.5,
        color=PALETTE["red"],
    )

    legend_handles = [
        Patch(facecolor=PALETTE["red"], edgecolor="white", label="Pushes toward self-repaid"),
        Patch(facecolor=PALETTE["blue_2"], edgecolor="white", label="Pushes toward non-self-repaid"),
    ]
    ax.legend(handles=legend_handles, loc="upper right", bbox_to_anchor=(1.0, -0.085), ncol=2, fontsize=9.5)

    fig.tight_layout(pad=0.55, rect=(0, 0.055, 1, 1))
    fig.savefig(output_pdf, bbox_inches="tight", pad_inches=0.04, dpi=300)
    fig.savefig(output_png, bbox_inches="tight", pad_inches=0.04, dpi=300)
    plt.close(fig)


def write_summary(
    selected_index: int,
    global_index: int,
    probability: float,
    prediction: int,
    true_label: int,
    base_value: float,
    final_value: float,
    items: list[dict[str, object]],
) -> None:
    """Write the selected-instance details used to reproduce the paper claim."""
    lines = [
        "# Figure 12 SHAP Waterfall Summary",
        "",
        "- Model: 55-feature XGBoost, temporal 80/20 split.",
        "- Instance selection: correctly predicted self-repaid hold-out case nearest the median predicted probability among correct positives.",
        f"- Test index: {selected_index}",
        f"- Global dataset index: {global_index}",
        f"- True label: {true_label}",
        f"- Predicted label: {prediction}",
        f"- Predicted probability: {probability:.4f}",
        f"- Base value: {base_value:.4f} log-odds",
        f"- Final value: {final_value:.4f} log-odds",
        "",
        "## Local Contributions",
        "",
        "| Rank | Feature | Processed value | SHAP contribution |",
        "|---:|---|---:|---:|",
    ]
    for rank, item in enumerate(items, start=1):
        value = item["feature_value"]
        value_text = "" if isinstance(value, float) and math.isnan(value) else f"{float(value):.4f}"
        lines.append(f"| {rank} | {item['feature']} | {value_text} | {float(item['contribution']):+.4f} |")

    summary_path = RESULTS_DIR / "xgboost_shap_waterfall_summary.md"
    summary_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  Wrote {summary_path}")


def main() -> None:
    """Regenerate the supplementary local waterfall without touching V4 Figure 12."""
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    FIGURES_DIR.mkdir(parents=True, exist_ok=True)

    records, df, y = pipeline.load_data(pipeline.DEFAULT_DATASET)
    split = pipeline.make_temporal_splits(records, train_percentages=[80])[0]
    y_test = y[split.train_size :]

    xgb_params = load_tuned_xgboost_params()
    model, x_test_df, shap_values, metrics, display_names = pipeline.run_shap(records, df, y, xgb_params)
    selected_index, probabilities, predictions = select_representative_positive(model, x_test_df, y_test)

    margins = logit(probabilities)
    base_values = margins - shap_values.sum(axis=1)
    base_value = float(np.mean(base_values))
    final_value = float(base_value + shap_values[selected_index].sum())
    probability = float(probabilities[selected_index])

    items = build_waterfall_items(
        feature_names=list(x_test_df.columns),
        feature_values=x_test_df.iloc[selected_index].to_numpy(),
        shap_row=shap_values[selected_index],
        top_n=12,
    )

    output_pdf = FIGURES_DIR / "xgboost_shap_temporal_waterfall.pdf"
    output_png = FIGURES_DIR / "xgboost_shap_temporal_waterfall.png"
    plot_waterfall(items, base_value, final_value, probability, output_pdf, output_png)

    print(f"  Wrote supplementary waterfall PDF to {output_pdf}")
    print(f"  Wrote supplementary waterfall PNG to {output_png}")

    write_summary(
        selected_index=selected_index,
        global_index=split.train_size + selected_index,
        probability=probability,
        prediction=int(predictions[selected_index]),
        true_label=int(y_test[selected_index]),
        base_value=base_value,
        final_value=final_value,
        items=items,
    )
    print(f"  Test metrics reused: AUC={metrics['auc']:.4f}, MCC={metrics['mcc']:.4f}")


if __name__ == "__main__":
    main()
